package cl.keber.characterization;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.client.TestRestTemplate;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;

import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Characterization tests for the {@code /programs} REST contract.
 *
 * <p>These tests pin the <em>observable</em> behaviour of the TrainingProgram slice
 * exactly as it behaves today, so that the Clean Architecture refactor can move code
 * between layers without silently changing what callers see. Several assertions below
 * pin behaviour that is arguably wrong; they are marked with a
 * {@code // characterization:} comment. Changing any of them is a deliberate contract
 * change, not a refactor.
 *
 * <p>The test runs against an in-memory H2 database configured explicitly here, so it
 * never connects to the shared Railway database. Flyway migrations V1-V5 are applied to
 * the {@code OTFSISACAD} schema, following the same pattern as
 * {@code TrainingProgramRepositoryTest}.
 *
 * <p>A real servlet container ({@code RANDOM_PORT} + {@link TestRestTemplate}) is used
 * rather than MockMvc on purpose: MockMvc rethrows unhandled controller exceptions to the
 * caller instead of producing a response, which would hide the actual HTTP status codes
 * the error paths return on the wire.
 *
 * <p>The context is shared across test methods and the database is not rolled back
 * between them, so every test uses its own unique {@code code} value and asserts by code
 * rather than by list size.
 */
@SpringBootTest(
    webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT,
    properties = {
        "spring.datasource.url=jdbc:h2:mem:characterization;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false",
        "spring.datasource.username=sa",
        "spring.datasource.password=",
        "spring.datasource.driver-class-name=org.h2.Driver",
        "spring.flyway.default-schema=OTFSISACAD",
        "spring.flyway.schemas=OTFSISACAD",
        "spring.jpa.properties.hibernate.default_schema=OTFSISACAD"
    })
class TrainingProgramApiCharacterizationTest {

    private static final String PROGRAMS = "/programs";

    @Autowired
    private TestRestTemplate rest;

    private final ObjectMapper objectMapper = new ObjectMapper();

    // --- POST /programs -----------------------------------------------------

    @Test
    @DisplayName("POST /programs returns 200 with the persisted program and a generated id")
    void createReturnsPersistedProgram() throws Exception {
        ResponseEntity<String> response = post(programJson(
            "CH-CREATE", "Occupational Health", "2025-07-01", "2025-07-15", "VIGENTE"));

        // characterization: create answers 200 OK, not the 201 Created a POST would normally return
        assertEquals(200, response.getStatusCode().value());

        JsonNode created = parse(response);
        assertNotNull(created.get("id"), "id is generated by the database and echoed back");
        assertFalse(created.get("id").isNull(), "id is generated by the database and echoed back");
        assertEquals("CH-CREATE", created.get("code").asText());
        assertEquals("Occupational Health", created.get("name").asText());
        assertEquals("2025-07-01", created.get("startDate").asText());
        assertEquals("2025-07-15", created.get("endDate").asText());
        assertEquals("VIGENTE", created.get("status").asText());
        // characterization: the JPA entity is the wire format; the response carries exactly
        // these six fields, including the database id. TrainingProgramDto is not used by the
        // controller at all.
        assertEquals(
            List.of("id", "code", "name", "startDate", "endDate", "status"),
            fieldNames(created));
    }

    @Test
    @DisplayName("A created program is returned by a subsequent GET /programs with the same values")
    void createdProgramIsReturnedByList() throws Exception {
        post(programJson("CH-ROUNDTRIP", "Round Trip", "2025-01-01", "2025-02-01", "VIGENTE"));

        JsonNode found = findByCode(list(), "CH-ROUNDTRIP");
        assertNotNull(found, "the created program must appear in the list");
        assertEquals("Round Trip", found.get("name").asText());
        assertEquals("2025-01-01", found.get("startDate").asText());
        assertEquals("2025-02-01", found.get("endDate").asText());
        assertEquals("VIGENTE", found.get("status").asText());
    }

    // --- GET /programs ------------------------------------------------------

    @Test
    @DisplayName("GET /programs returns 200 and a JSON array")
    void listReturnsJsonArray() throws Exception {
        ResponseEntity<String> response = rest.getForEntity(PROGRAMS, String.class);

        assertEquals(200, response.getStatusCode().value());
        assertTrue(parse(response).isArray(), "the list endpoint returns a bare JSON array");
    }

    // --- PUT /programs/{id} -------------------------------------------------

    @Test
    @DisplayName("PUT /programs/{id} with a matching id in the body updates the persisted program")
    void updateWithMatchingIdChangesPersistedValues() throws Exception {
        long id = parse(post(programJson(
            "CH-UPDATE", "Before Update", "2025-03-01", "2025-04-01", "VIGENTE"))).get("id").asLong();

        ResponseEntity<String> response = exchange(HttpMethod.PUT, PROGRAMS + "/" + id,
            "{\"id\":" + id + ",\"code\":\"CH-UPDATE\",\"name\":\"After Update\","
                + "\"startDate\":\"2025-03-05\",\"endDate\":\"2025-04-05\",\"status\":\"CERRADO\"}");

        assertEquals(200, response.getStatusCode().value());
        JsonNode updated = parse(response);
        assertEquals(id, updated.get("id").asLong());
        assertEquals("After Update", updated.get("name").asText());
        assertEquals("2025-03-05", updated.get("startDate").asText());
        assertEquals("2025-04-05", updated.get("endDate").asText());
        assertEquals("CERRADO", updated.get("status").asText());

        JsonNode persisted = findById(list(), id);
        assertNotNull(persisted, "the updated program is still listed");
        assertEquals("After Update", persisted.get("name").asText());
        assertEquals("CERRADO", persisted.get("status").asText());
    }

    @Test
    @DisplayName("PUT /programs/{id} without an id in the body inserts a second program instead of updating")
    void updateWithoutIdInBodyInsertsAnotherProgram() throws Exception {
        long id = parse(post(programJson(
            "CH-PUT-NO-ID", "Original", "2025-05-01", "2025-06-01", "VIGENTE"))).get("id").asLong();

        ResponseEntity<String> response = exchange(HttpMethod.PUT, PROGRAMS + "/" + id,
            programJson("CH-PUT-NO-ID", "Attempted Update", "2025-05-01", "2025-06-01", "VIGENTE"));

        assertEquals(200, response.getStatusCode().value());

        // characterization: pins current behaviour, not desired behaviour.
        // UpdateTrainingProgramUseCase verifies that {id} exists, then calls
        // repository.save(updated) with the *request body* entity. When the body carries no
        // id, JPA treats it as a new row, so the PUT silently INSERTS a duplicate and leaves
        // the addressed program untouched. The frontend must send the id in the body today.
        JsonNode inserted = parse(response);
        assertNotEquals(id, inserted.get("id").asLong(),
            "the response carries a newly generated id, not the id from the path");

        JsonNode original = findById(list(), id);
        assertNotNull(original, "the addressed program still exists");
        assertEquals("Original", original.get("name").asText(),
            "the addressed program was NOT updated");

        assertEquals(2, countByCode(list(), "CH-PUT-NO-ID"),
            "the PUT created a duplicate row rather than updating in place");
    }

    @Test
    @DisplayName("PUT /programs/{id} for an unknown id returns 404")
    void updateOnMissingIdReturnsNotFound() {
        ResponseEntity<String> response = exchange(HttpMethod.PUT, PROGRAMS + "/999999",
            programJson("CH-MISSING", "Nobody", "2025-07-01", "2025-07-15", "VIGENTE"));

        // behaviour change: approved 2026-08-31.
        // Was: 500. TrainingProgramNotFoundException carried no @ResponseStatus and no
        // @ControllerAdvice existed, so it escaped the dispatcher unhandled. Now
        // RestExceptionHandler maps it to 404, which is the honest answer for a PUT that
        // addresses an id nothing is stored under (decisions D1 and D11). The exception is
        // thrown from the same place as before - the existence check at the top of
        // TrainingProgramApplicationService.execute(Long, UpdateTrainingProgramCommand) -
        // so only the status code changed, not when the failure happens.
        assertEquals(404, response.getStatusCode().value());
        assertErrorBody(response, 404, "Not Found");
    }

    @Test
    @DisplayName("PUT /programs/{id} with a different id in the body returns 400")
    void updateWithMismatchedIdReturnsBadRequest() throws Exception {
        long id = parse(post(programJson(
            "CH-MISMATCH", "Mismatch", "2025-08-01", "2025-09-01", "VIGENTE"))).get("id").asLong();

        ResponseEntity<String> response = exchange(HttpMethod.PUT, PROGRAMS + "/" + id,
            "{\"id\":" + (id + 100000) + ",\"code\":\"CH-MISMATCH\",\"name\":\"X\","
                + "\"startDate\":\"2025-08-01\",\"endDate\":\"2025-09-01\",\"status\":\"VIGENTE\"}");

        // behaviour change: approved 2026-08-31.
        // Was: 500. The id-mismatch guard has always thrown IllegalArgumentException, but
        // nothing handled it. RestExceptionHandler now maps it to 400, which is correct: a
        // body id contradicting the path id is a malformed request, not a server fault
        // (decisions D1 and D11). The guard itself is untouched - the path id and the body id
        // remain separate arguments to the update use case.
        assertEquals(400, response.getStatusCode().value());
        assertErrorBody(response, 400, "Bad Request");
    }

    // --- DELETE /programs/{id} ----------------------------------------------

    @Test
    @DisplayName("DELETE /programs/{id} returns 204 and removes the program from the list")
    void deleteRemovesProgramFromList() throws Exception {
        long id = parse(post(programJson(
            "CH-DELETE", "To Be Deleted", "2025-10-01", "2025-11-01", "VIGENTE"))).get("id").asLong();
        assertNotNull(findById(list(), id), "precondition: the program exists");

        ResponseEntity<String> response = exchange(HttpMethod.DELETE, PROGRAMS + "/" + id, null);

        assertEquals(204, response.getStatusCode().value());
        assertNull(response.getBody(), "delete answers with an empty body");
        assertNull(findById(list(), id), "the deleted program is no longer listed");
    }

    @Test
    @DisplayName("DELETE /programs/{id} for an unknown id returns 204")
    void deleteOnMissingIdReturnsNoContent() {
        ResponseEntity<String> response = exchange(HttpMethod.DELETE, PROGRAMS + "/999999", null);

        // characterization: pins current behaviour, not desired behaviour.
        // Spring Data's deleteById is a no-op for an absent id, so delete is idempotent and
        // never reports 404. Callers cannot distinguish "deleted" from "was never there".
        assertEquals(204, response.getStatusCode().value());
    }

    // --- Validation is not enforced over HTTP -------------------------------

    @Test
    @DisplayName("POST /programs rejects a blank code and does not persist it")
    void createWithBlankCodeIsRejected() throws Exception {
        ResponseEntity<String> response = post(programJson(
            "", "Blank Code", "2025-07-01", "2025-07-15", "VIGENTE"));

        // behaviour change: approved 2026-08-30.
        // Was: 200 and persisted. The validating constructor was bypassed because Jackson bound
        // the request through the no-arg constructor and wrote the private fields directly.
        // Now: the controller binds TrainingProgramDto and maps it through the domain, so
        // TrainingProgramCode rejects the blank value. This is exposed defect 1 being closed.
        //
        // behaviour change: approved 2026-08-31.
        // Was: the 500 WP3 left behind, only because no advice existed yet. WP7 adds it, so the
        // IllegalArgumentException TrainingProgramCode raises now surfaces as the 400 this
        // request always deserved (decisions D1 and D11). The rejection itself is unchanged -
        // only its status code is - and the program is still not persisted.
        assertEquals(400, response.getStatusCode().value());
        assertErrorBody(response, 400, "Bad Request");
        assertNull(findByName(list(), "Blank Code"), "the invalid program is not persisted");
    }

    @Test
    @DisplayName("POST /programs rejects an endDate before the startDate and does not persist it")
    void createWithEndDateBeforeStartDateIsRejected() throws Exception {
        ResponseEntity<String> response = post(programJson(
            "CH-INVERTED", "Inverted Dates", "2025-07-15", "2025-07-01", "VIGENTE"));

        // behaviour change: approved 2026-08-30.
        // Was: 200 and persisted, because the "endDate must be after startDate" rule lived only
        // in a constructor the HTTP path never reached. Now the rule lives in the TrainingPeriod
        // value object, which the request body must pass through. Exposed defect 1 again.
        //
        // behaviour change: approved 2026-08-31.
        // Was: the placeholder 500 WP3 recorded pending the advice. TrainingPeriod's
        // IllegalArgumentException now maps to 400 (decisions D1 and D11). An inverted date
        // range is caller error, so 400 is the correct code; the validation and the
        // not-persisted guarantee below are unchanged.
        assertEquals(400, response.getStatusCode().value());
        assertErrorBody(response, 400, "Bad Request");
        assertNull(findByCode(list(), "CH-INVERTED"), "the invalid program is not persisted");
    }

    @Test
    @DisplayName("POST /programs with a null code returns 400")
    void createWithNullCodeReturnsBadRequest() {
        ResponseEntity<String> response = post(programJson(
            null, "Null Code", "2025-07-01", "2025-07-15", "VIGENTE"));

        // behaviour change: approved 2026-08-31.
        // Was: 500. Originally the only thing rejecting a null code was the NOT NULL constraint
        // on training_program.code, whose DataIntegrityViolationException went unhandled. Since
        // WP3 the request is rejected earlier, by TrainingProgramCode, and WP7's advice maps
        // that IllegalArgumentException to 400 (decisions D1 and D11). The request is still
        // rejected and still never reaches the database - it now says so honestly.
        assertEquals(400, response.getStatusCode().value());
        assertErrorBody(response, 400, "Bad Request");
    }

    @Test
    @DisplayName("POST /programs with an empty JSON object returns 400")
    void createWithEmptyBodyReturnsBadRequest() {
        ResponseEntity<String> response = post("{}");

        // behaviour change: approved 2026-08-31.
        // Was: 500 from the database constraint. Same cause and same justification as the null
        // code above - every field is missing, so TrainingProgramCode rejects the body first and
        // the advice turns that IllegalArgumentException into 400 (decisions D1 and D11).
        assertEquals(400, response.getStatusCode().value());
        assertErrorBody(response, 400, "Bad Request");
    }

    @Test
    @DisplayName("POST /programs with malformed JSON returns 400")
    void createWithMalformedJsonReturnsBadRequest() {
        ResponseEntity<String> response = post("this is not json");

        assertEquals(400, response.getStatusCode().value());
        assertErrorBody(response, 400, "Bad Request");
    }

    // --- Routing ------------------------------------------------------------

    @Test
    @DisplayName("GET /programs/{id} returns 405 because no read-by-id endpoint is mapped")
    void getByIdReturnsMethodNotAllowed() {
        ResponseEntity<String> response = rest.getForEntity(PROGRAMS + "/1", String.class);

        // characterization: pins current behaviour, not desired behaviour.
        // GetTrainingProgramUseCase exists but no controller method exposes it, and WP7 did not
        // add one: routing it would be a new feature, not a refactor (decision D5). The path
        // /programs/{id} is mapped for PUT and DELETE only, so a GET is rejected as 405 Method
        // Not Allowed rather than 404 Not Found.
        assertEquals(405, response.getStatusCode().value());
    }

    // --- Helpers ------------------------------------------------------------

    private ResponseEntity<String> post(String json) {
        return exchange(HttpMethod.POST, PROGRAMS, json);
    }

    private ResponseEntity<String> exchange(HttpMethod method, String url, String json) {
        HttpEntity<String> entity = null;
        if (json != null) {
            HttpHeaders headers = new HttpHeaders();
            headers.setContentType(MediaType.APPLICATION_JSON);
            entity = new HttpEntity<>(json, headers);
        }
        return rest.exchange(url, method, entity, String.class);
    }

    private JsonNode list() throws Exception {
        ResponseEntity<String> response = rest.getForEntity(PROGRAMS, String.class);
        assertEquals(200, response.getStatusCode().value());
        return parse(response);
    }

    private JsonNode parse(ResponseEntity<String> response) throws Exception {
        return objectMapper.readTree(response.getBody());
    }

    private static String programJson(
            String code, String name, String startDate, String endDate, String status) {
        return "{\"code\":" + quote(code)
            + ",\"name\":" + quote(name)
            + ",\"startDate\":" + quote(startDate)
            + ",\"endDate\":" + quote(endDate)
            + ",\"status\":" + quote(status) + "}";
    }

    private static String quote(String value) {
        return value == null ? "null" : "\"" + value + "\"";
    }

    private static List<String> fieldNames(JsonNode node) {
        List<String> names = new ArrayList<>();
        node.fieldNames().forEachRemaining(names::add);
        return names;
    }

    private static JsonNode findByCode(JsonNode array, String code) {
        for (JsonNode node : array) {
            if (code.equals(node.path("code").asText(null))) {
                return node;
            }
        }
        return null;
    }

    private static JsonNode findByName(JsonNode array, String name) {
        for (JsonNode node : array) {
            if (name.equals(node.path("name").asText(null))) {
                return node;
            }
        }
        return null;
    }

    private static JsonNode findById(JsonNode array, long id) {
        for (JsonNode node : array) {
            if (node.path("id").asLong(-1L) == id) {
                return node;
            }
        }
        return null;
    }

    private static int countByCode(JsonNode array, String code) {
        int count = 0;
        for (JsonNode node : array) {
            if (code.equals(node.path("code").asText(null))) {
                count++;
            }
        }
        return count;
    }

    private void assertErrorBody(ResponseEntity<String> response, int status, String error) {
        // Spring Boot's default error body: timestamp, status, error, path.
        String body = response.getBody();
        assertNotNull(body, "the default error handler returns a JSON body");
        assertTrue(body.contains("\"status\":" + status), "error body reports status " + status);
        assertTrue(body.contains("\"error\":\"" + error + "\""), "error body reports " + error);
    }
}
