name: Java CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_DATABASE: ${{ secrets.DB_DATABASE }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build with Maven
      run: mvn clean compile
  
  test:
<<<<<<< HEAD
    name: Run Tests
=======
    name: Run Tests and Upload Coverage
>>>>>>> 56a68ac (refactor: improvements in ci pipeline jobs)
    runs-on: ubuntu-latest
    needs: build
    continue-on-error: ${{ github.ref != 'refs/heads/main' }}
    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_DATABASE: ${{ secrets.DB_DATABASE }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Run tests
      run: mvn verify
      
    - name: Generate Test badge
      if: success() || failure()
      uses: gaelgirodon/ci-badges-action@v1
      with:
        gist-id: ${{ secrets.GIST_ID }} 
        token: ${{ secrets.GIST_TOKEN }}

    - name: Upload reports
      uses: actions/upload-artifact@v4
      with:
        name: maven-test-reports
        path: |
          target/site/jacoco/
          target/site/surefire-report/

  frontend:
    name: Build and Test Frontend
    runs-on: ubuntu-latest
    if: ${{ contains(join(github.event.commits.*.modified, ' '), 'frontend/') }}

    defaults:
      run:
        working-directory: frontend
        
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci
      
      - name: Build frontend tests
        run: npm test -- --watchAll=false

      - name: Build frontend
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: frontend/build

  publish-reports:
<<<<<<< HEAD
    name: Upload Coverage and Publish Reports to GitHub Pages
=======
    name: Publish Reports to GitHub Pages
>>>>>>> 56a68ac (refactor: improvements in ci pipeline jobs)
    needs: test
    if: always()
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
<<<<<<< HEAD
    - name: Compile for Sonar
      run: mvn compile

=======
>>>>>>> 56a68ac (refactor: improvements in ci pipeline jobs)
    - name: Download reports
      uses: actions/download-artifact@v4
      with:
        name: maven-test-reports
        path: target/site/

    - name: Run SonarCloud analysis
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn sonar:sonar

    - name: Upload coverage to Codecov
      if: success() || failure()
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: target/site/jacoco/jacoco.xml
        flags: unittests
        name: codecov-coverage
        fail_ci_if_error: true

    - name: Combine JaCoCo and Surefire reports
      if: success() || failure()
      run: |
        mkdir -p target/site/combined
        cp -r target/site/jacoco target/site/combined/coverage
        cp -r target/site/surefire-report target/site/combined/tests
        cp target/site/surefire-report/surefire-report.html target/site/combined/tests/index.html

    - name: Deploy reports to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target/site/combined
        force_orphan: true

