name: Java CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build and test
      run: mvn clean verify

    - name: Upload JaCoCo report
      uses: actions/upload-artifact@v4
      with:
        name: jacoco-report
        path: target/site/jacoco/

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: target/site/jacoco/jacoco.xml
        flags: unittests
        name: codecov-coverage
        fail_ci_if_error: true

    - name: Generate Test badge
      uses: gaelgirodon/ci-badges-action@v1
      with:
        gist-id: ${{ secrets.GIST_ID }} 
        token: ${{ secrets.GIST_TOKEN }}

  deploy-pages:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build and generate report
      run: mvn clean verify

    - name: Run SonarCloud analysis
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn sonar:sonar


    - name: Generate Surefire HTML report
      run: mvn surefire-report:report-only


    - name: Combine JaCoCo and Surefire reports
      run: |
        mkdir -p target/site/combined
        cp -r target/site/jacoco target/site/combined/coverage
        cp -r target/site/surefire-report target/site/combined/tests
        cp target/site/surefire-report/surefire-report.html target/site/combined/tests/index.html

    - name: Deploy reports to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target/site/combined

